name: ENV ACT
description: Create env

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Create env
      shell: bash
      run: |
        export IMAGE=gcr.io/hello-world/hello-me:$GITHUB_SHA
        echo $IMAGE

    - name: ECHO env
      shell: bash
      run: |
        echo $IMAGE
    
    - name: Update env
      shell: bash
      run: |
        echo ${{ env.TEMP_IMAGE }}

    - name: ECHO env
      shell: bash
      run: |
        echo ${{ env.TEMP_IMAGE }}
