name: ENV ACT
description: Create env

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Create env
      shell: bash
      env:
        IMAGE: gcr.io/hello-world/hello-me:latest
      run: |
        echo $IMAGE

    - name: ECHO env
      shell: bash
      run: |
        echo $IMAGE
    
    - name: Update env
      shell: bash
      env:
        IMAGE: gcr.io/bye-world/bye-me:latest
      run: |
        echo $IMAGE

    - name: ECHO env
      shell: bash
      run: |
        echo $IMAGE

