name: Manual-Workflow

on: [workflow_dispatch]
# WORKFLOW_ACTION
permissions:
  contents: write
  id-token: write

env:
  TEMP_IMAGE: gcr.io/bye-world/bye-me:$GITHUB_SHA

jobs:
  
  branch-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run hello world
        run: echo "Hello Branch Pipeline!"
      
      - name: create txt file
        run: echo "original workflow"

      # - name: call repository dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.ACTIONS_TOKEN }}
      #     repository: VishwasD47/Test
      #     event-type: test_result

      # - name: set up kustomize
      #   run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      # - name: check version
      #   run: kustomize version

      - name: call composite action
        uses: ./.github/actions/env-act 